<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Offerte\Module'                        => __DIR__ . '/Module.php',
    'Offerte\Controller\OfferteController' => __DIR__ . '/src/Offerte/Controller/OfferteController.php',
    'OfferteTest\Framework\TestCase'        => __DIR__ . '/tests/Offerte/Framework/TestCase.php',
    'OfferteTest\SampleTest'                => __DIR__ . '/tests/Offerte/SampleTest.php',
);
